dprojx/dappx/urls.py
# dappx/urls.py
from django.conf.urls import url
from dappx import views
# SET THE NAMESPACE!
app_name = 'dappx'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

dprojx/dprojx/urls.py
# dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dappx import views
from lecturer import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^lecturer/',include('lecturer.urls')),

]

dprojx/lecturer/urls.py
# dappx/urls.py
from django.conf.urls import url
from lecturer import views
# SET THE NAMESPACE!
app_name = 'lecturer'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

dprojx/dappx/models.py
# dappx/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    # profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    student_number = models.IntegerField(blank=True,default = "1" , primary_key=True)
    regno = models.CharField(max_length=30, unique=True, default = "default")
    names = models.CharField(max_length=60, default = "default")
    DOB = models.DateField(null=True)
    year_of_study = models.IntegerField(blank=True, default = "default")
    def __str__(self):
        return self.user.username

dprojx/lecturer/models.py
# dappx/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class LecturerInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=30, null=True)
    college = models.CharField(max_length=30)
    department = models.CharField(max_length=30, null=True)
    lecturer_id = models.IntegerField()
    def __str__(self):
        return self.user.username

dprojx/dappx/forms.py
# dappx/forms.py
from django import forms
from dappx.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic','student_number','regno','names','DOB','year_of_study')

dprojx/lecturer/forms.py
# dappx/forms.py
from django import forms
from lecturer.models import LecturerInfo
from django.contrib.auth.models import User
class LecturerForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class LecturerInfoForm(forms.ModelForm):
    class Meta():
        model = LecturerInfo
        fields = ('name', 'college', 'department', 'lecturer_id')

dprojx/dappx/views.py
from django.shortcuts import render
from dappx.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from dappx.models import UserProfileInfo
from django.contrib.auth.decorators import login_required
def index(request):
    return render(request,'dappx/index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'dappx/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                data = UserProfileInfo.objects.all()

                stu = {
                    "student_number": data
                    }
                
                return render(request, "dappx/index.html", stu)
 
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dappx/login.html', {})

dprojx/lecturer/views.py
from django.shortcuts import render
from lecturer.forms import LecturerForm,LecturerInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from lecturer.models import LecturerInfo
from django.contrib.auth.decorators import login_required
def index(request):
    return render(request,'dappx/index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = LecturerForm(data=request.POST)
        profile_form = LecturerInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = LecturerForm()
        profile_form = LecturerInfoForm()
    return render(request,'dappx/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                data1 = LecturerInfo.objects.all()

                stu = {
                    "lecturer_id": data1
                    }
                
                return render(request, "dappx/index2.html", stu)
 
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dappx/login2.html', {})

dprojx/templates/dappx/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Online Chat</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'dappx:register' %}">Subscribe</a></li> 
          <li><a class="navbar-link" href="{% url 'lecturer:register' %}">Lecturer</a></li> 
  
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'dappx:user_login' %}">Login</a></li>
            <li><a class="navbar-link" href="{% url 'lecturer:user_login' %}">Lecturer Login</a></li>

          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

dprojx/templates/dappx/index.html
{% extends "dappx/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the GROUP X4 chat app!</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        <p>
        Names | RegNo | Date Of Birth | Year of Student <br>
        {% for student in student_number %}
        {{ student.names}} 
        {{ student.regno}}
        {{ student.student_number}}
        {{student.DOB }}
        {{ student.year_of_study }} </p>

        {% endfor %}



    {% else %}
        <h2>Subcribe or Login if you'd like to take part</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

dprojx/templates/dappx/index2.html
{% extends "dappx/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Group X4 chat app!</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        Name | College | Department | ID No.<br>
        <p>
        {% for lecturer in lecturer_id %}
        {{ lecturer.name}}
        {{ lecturer.college}}
        {{ lecturer.department}}
        {{lecturer.lecturer_id }} </p>

        {% endfor %}

    {% else %}
        <h2>Subcribe or Login if you'd like to take part</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

dprojx/templates/dappx/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>
    
        Login

    </h1>
    <form method="post" action="{% url 'dappx:user_login' %}">
      {% csrf_token %}
      {# A more "HTML" way of creating the login form#}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Username">
      <label for="password">Password:</label>
      <input type="password" name="password" placeholder="Password">
      <input type="submit" name="" value="Login">
    </form>
  </div>
</div>
{% endblock %}

dprojx/templates/dappx/login2.html
{% extends 'dappx/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h2>Lecturer Login</h2>
<form method="post" action="{% url 'lecturer:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

dprojx/templates/dappx/registration.html
{% extends "dappx/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}